BIN=megaphone
CC= c++
CFLAGS = -Werror -Wall -Wextra -std=c++98
CFLAGS += -g3

SRC_FILE= megaphone.cpp \
		  

SRC_DIR=./Src/
SRC:= $(addprefix $(SRC_DIR), $(SRC_FILE))

all:
	$(CC) $(CFLAGS) $(SRC) -o $(BIN)

